ci: migrate to GH actions
ShabadOS/gurmukhi-utils pull request #171
Opened 2020-10-20 16:44 UTC by saihaj

### Summary of PR
Migrate CCI workflow to GH actions. I split it into 2 workflows one for CI which runs tests and listing and CD for building and deploying to NPM

### For Maintainers
* [ ] Setup secret `NPM_BOT_TOKEN`

### Time spent on PR
30 mins

### Demo
For some reason `npm run publish-coverage` is not working. I don't know if this is something I need add a secret or something for coveralls.
https://github.com/saihaj/ShabadOSgurmukhi-utils/runs/1282232803?check_suite_focus=true

### Linked issues
Ongoing migration process 

### Reviewers
@Harjot1Singh @bhajneet

2020-10-21 20:08 UTC, Harjot1Singh requested changes

2020-10-21 20:08 UTC, Harjot1Singh commented on .github/workflows/ci.yml
> +      - name: Publish Coverage Report
Scrap this, remove it from package.json, use https://github.com/marketplace/actions/coveralls-github-action instead. Having this command is not useful offline.

2020-10-23 14:49 UTC, saihaj commented
I rebased mine with dev. I think it probably has something to do with readme 🤷🏼‍♂️ ?

2020-10-25 16:50 UTC, Harjot1Singh requested changes
Great work, just this one change!

2020-10-25 16:50 UTC, Harjot1Singh commented on package.json
> +    "test:coverage": "jest --coverage",
tbh, i'd just scrap this and add coverage by default to the test command, and just use that

2020-10-25 22:38 UTC, Harjot1Singh approved these changes

2020-10-26 02:32 UTC, merged